name: Validate with hassfest

on:
  push:
  pull_request:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
        with:
          category: integration
          integration: crestron_home
